### ISSUE TITLE
Do input solutions have to compile?

### ISSUE THREAD

**Issue by urialon** [microsoft/graph-based-code-modelling#4]
Hi @mmjb ,
I noticed that your code tries to build every input solution.
Do these input solutions **have** to compile/ build successfully?

If so, what happens when they don't? Because your code doesn't simply skip an unbuilt solution.

Thanks!

**Comment by RoySadaka** [comment]
+1

**Comment by mmjb** [comment]
Building successfully is not required, but building "enough" is so that Roslyn semantic model is populated with type information, which is crucial to determine which expressions to consider. [This means that nuget package need to be around, at least]

**Comment by urialon** [comment]
Thanks!
