### ISSUE TITLE
Running on languages other than C#?

### ISSUE THREAD

**Issue by ywen666** [Microsoft/graph-based-code-modelling#8]
Hi,

Thanks for releasing this amazing library!

I am trying to build this library on top of java codebase, i wonder if there is any high level guideline to run the code on languages other than C#.

For example, do I need to redo everything in ExpressionDataExtractor and SourceGraphExtractionUtils for java to allow the python models in Models/ to take java code as the legitimate input?

Or I can generate my own java AST (and probably my own meta-date?), and use this as the input to the python models in Models/?

Thanks!

**Comment by mmjb** [comment]
Heya,

Thanks for reaching out. Currently, there is no support for any language than C#. As you observe, you roughly need to replace the ExpressionDataExtractor and the SourceGraphExtractionUtils to generate similar data. There are a number of partial solutions for this for other languages (e.g., https://github.com/acr31/features-javac implements graph extraction for Java) that you could possible re-use.

Marc
